spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: trorapi
        uri: http://localhost:8081
        predicates:
        - Path=/api/hello
        filters:
        - RewritePath=/api/hello, /tror/hello
      - id: tror
        uri: http://localhost:8081
        predicates:
        - Path=/**/hello
      - id: pma
        uri: http://localhost:8082
        predicates:
        - Path=/hi
        filters:
        - PrefixPath=/pma
server:
  port: 8080
  display-name: ${spring.application.name}
#  servlet:
#    context-path: /api

logging:
  level:
    root: debug
    org.springframework.cloud.gateway: debug